### ISSUE TITLE
6. 배포

### ISSUE THREAD

**Issue by kyeahen** [yoonhoGo/serverless-spa-portfolio#3]
sls deploy [-v] [--aws-profile <name>]
여기서 [] 부분을 생략해도 되는 부분이라고 직관적으로 안내하면 더 좋을 것 같습니다!

**Comment by kyeahen** [comment]
저는 배포 과정에서

>  User: arn:aws:iam::014251652175:user/kyeahen is not authorized to perform: cloudformation:CreateStack on resource: arn:aws:cloudformation:ap-northeast-2:014251652175:stack/MyPortfolio-dev/*

이러한 에러가 났었는데 IAM에서 AdministratorAccess 권한을 추가하니까 배포가 되더라구요.
이러한 문제도 고려하시면 좋을 것 같습니당!!

**Comment by yoonhoGo** [comment]
아하 실습환경때는 항상 AdministratorAccess 권한을 줘서 신경쓰지 못했는데 중요한 포인트를 집어주셨네요 ㅎㅎ
감사합니다 ^^
