### ISSUE TITLE
awscli 설치

### ISSUE THREAD

**Issue by yebonkim** [yoonhoGo/serverless-spa-portfolio#4]
awscli 설치 관련 명령어가 들어가면 좋을 것 같습니다 ㅎㅎ 저는 안깔려있어서요..ㅎㅎㅎ...

**Comment by yoonhoGo** [comment]
3-5번에 i, ii 번이 선택적인 부분이라 serverless로 하셔도 됬는데 그 설명이 없었네요 ㅎㅎ
설명 추가 했습니다
