### ISSUE TITLE
Route Not Found 오류

### ISSUE THREAD

**Issue by yebonkim** [yoonhoGo/serverless-spa-portfolio#5]
{
statusCode: 404,
error: "Serverless-offline: route not found.",
currentRoute: "get - /",
existingRoutes: [ ],
}

처음 npm run start --stage=local
를 실행하였을 때 위와 같은 오류가 났습니닷

**Comment by kyeahen** [comment]
저도 같은 에러 발생했습니당!

**Comment by jh8579** [comment]
serverless.yml function에서 밑에 설정 안해줘서 그런 것 같은데   
http:
          path: /
          method: get

serverless.yml 설정하는 것 추가해야 할 것 같습니다!
